version: "3.8"

services:
  fe-sipdhub-prod:
    container_name: fe-sipdhub-prod
    image: fe-sipdhub-prod
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./src:/app/src
    ports:
      - "80:80"
    networks:
      - sipdhub
#  nginx:
#    image: nginx:latest
#    restart: always
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - "80:80"  # Exposing NGINX to the host on port 80
#    networks:
#      - sipdhub
#    depends_on:
#      - fe-sipdhub-dev
networks:
  sipdhub:
    external: true
