version: "3.8"

services:
  fe-sipdhub-dev:
    container_name: fe-sipdhub-dev
    image: fe-sipdhub-dev
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-build.dev
    volumes:
      - ./src:/app/src
    expose:
      - "3000"
    networks:
      - sipdhub
  # nginx:
  #   image: nginx:latest
  #   restart: always
  #   volumes:
  #     - ./nginx-dev.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "80:80"  # Exposing NGINX to the host on port 80
  #   networks:
  #     - sipdhub
  #   depends_on:
  #     - fe-sipdhub-dev
networks:
  sipdhub:
    external: true
