FROM node:20-alpine AS build

# Add a work directory
WORKDIR /app

# Cache and Install dependencies
#COPY /public/ /app/public
COPY package.json ./
COPY yarn.lock ./
#COPY /.env /app
RUN yarn install
# COPY . .
# RUN yarn run build
COPY /build /app/build
# Copy app files
COPY . .

FROM nginx:latest
EXPOSE 80
COPY /nginx-dev2.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

# Start the app
#CMD [ "yarn", "start" ]
