FROM imbios/bun-node:latest-current-alpine AS development
ENV NODE_ENV development
ENV NPM_CONFIG_LOGLEVEL warn

WORKDIR /app

# Copy package.json and bun.lockb first, then install dependencies
COPY package.json /app/
COPY bun.lockb /app/

# Install global dependencies
RUN npm i -g pm2

# Install Bun dependencies
RUN bun install

# Cache and Install dependencies
COPY bin /app/bin
COPY config /app/config
COPY helpers /app/helpers
COPY middleware /app/middleware
COPY routes /app/routes
COPY service /app/service
COPY pm2.config.js /app/
COPY .env /app/

# Copy app files
COPY . .

# run the app
#USER bun
EXPOSE 9011
# Start the app
CMD [ "yarn", "run", "prod" ]