FROM node:20-alpine AS build

# Add a work directory
WORKDIR /app

# Cache and Install dependencies
#COPY /public/ /app/public
COPY /package.json /app
COPY /yarn.lock /app
#COPY /.env /app
RUN yarn install
COPY . /app
COPY /build /app/build
# Copy app files
#COPY . .

FROM nginx:latest
EXPOSE 80
COPY /nginx-dev2.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

# Start the app
#CMD [ "yarn", "start" ]
