version: "3.8"

services:
  fe-sipdhub-prod:
    container_name: fe-sipdhub-prod
    image: fe-sipdhub-prod
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    expose:
      - "3000"
    network_mode: bridge
      # - sipdhub
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx-dev2.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"  # Exposing NGINX to the host on port 80
    network_mode: bridge
      # - sipdhub
    depends_on:
      - fe-sipdhub-prod
# networks:
  # sipdhub:
    # external: true
