version: "3.8"

services:
  app:
    container_name: fe-sipdhub-dev
    image: fe-sipdhub-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    expose:
      - "3000"
    networks:
      - sipdhub
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"  # Exposing NGINX to the host on port 80
    networks:
      - sipdhub
networks:
  sipdhub:
    external: true
