events {
  worker_connections 1024; # Specifies the maximum number of simultaneous connections per worker
}

http {
  upstream users-pendapatan-service {
    server users-pendapatan-service:9011;
  }

  server { 
    listen 9011;

    location / {
      proxy_pass http://users-pendapatan-service;
      rewrite ^/users-pendapatan-service(/.*)$ $1 break;
      proxy_set_header Accept-Encoding "x-sipdhub";
      proxy_redirect off;
      proxy_set_header Host $host:$server_port;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Optional: Handle static assets for frontend if needed
    # location /static/ {
    #  root /app;
    #}
  }
}

