#events {
#  worker_connections 1024; # Specifies the maximum number of simultaneous connections per worker
#}

server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
